- name: Install git on the host
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone the getting-started-app repository
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_dest }}"
    version: main
    force: yes

- name: Create Dockerfile inside cloned repository
  copy:
    dest: "{{ app_dest }}/Dockerfile"
    content: |
      FROM node:20-alpine
      WORKDIR /app
      COPY . .
      RUN npm install --omit=dev
      CMD ["node", "src/index.js"]
      EXPOSE 3000
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Build the application Docker image from cloned source
  community.docker.docker_image:
    name: "{{ app_image }}"
    build:
      path: "{{ app_dest }}"
    source: build

- name: Run the application container
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    image: "{{ app_image }}:latest"
    state: started
    restart_policy: always
    published_ports:
      - "{{ app_port_host }}:{{ app_port_container }}"

- name: Show that vault decryption works
  debug:
    msg: "Success! Decrypted simulated admin password from Vault: {{ vault_app_admin_password }}"
